name: ecommerce_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.3.2

dependencies:
  cached_network_image:
  carousel_slider_plus:
  flutter:
    sdk: flutter
  flutter_screenutil:
  flutter_slidable:
  auto_size_text:
  colornames:
  flutter_svg:
  flutter_native_splash:
  readmore:
  smooth_page_indicator:
  dio:
  toastification:
  flutter_bloc:
  shared_preferences:
  # add injectable to your dependencies
  injectable:
  # add get_it
  get_it:
  pretty_dio_logger: ^1.4.0

  lottie: ^3.1.2
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  # add the generator to your dev_dependencies
  injectable_generator:
  # add build runner if not already added
  build_runner:

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/svg_images/
    - assets/
    - assets/fonts/



  fonts:
     - family: Poppins
       fonts:
         - asset: assets/fonts/Poppins-.ttf



